#!/usr/bin/env python
import os, sys, argparse

DESCRIPTION = \
"""
wikitable - Convert a .csv file (tab separated)
            to Wiki table format. 
"""

EPILOG = \
"""
Running with no parameters will launch the GUI.
"""

DEVMODPATH = ['pywikitable']

# If the development module source paths exist, 
# add them to the python path
for mypath in DEVMODPATH:
    if ( os.path.exists(mypath) and \
                       (os.path.isfile(mypath) == False) ):
        sys.path.insert(0,mypath)
#print('Python path = %s'%(sys.path))

"""
The main app class.
Only gets called if this file is running stand alone, and
not if it's included as part of a larger application
"""
class theApp():        
    def __init__(self):
        self.appMain()

    def getVersion(self):
        from pywikitable import WikiTable
        vapp = WikiTable()
        version = '%(prog) s ' + vapp.__version__()
        return version        

    def getArgs(self):
        parser = argparse.ArgumentParser(\
                               description = DESCRIPTION,
                                           epilog = EPILOG)
        parser.add_argument('-v', '--version', 
                                   action='version', 
                                   version = self.getVersion())
        parser.add_argument("-i", "--inputfile", 
            default=None,
            help="Specifies the .csv input file name.")
        parser.add_argument("-o", "--outputfile", 
            default=None,
            help="Specifies the output file name for resulting" \
                +" Wiki page source code.")
        parser.add_argument("-d", "--delimiter", 
            default='\t',
            help='Specifies the .csv file field delimiter.\n' + \
                 'Can be any character or string\n'
                 'default is TAB(\'\t\')')
        parser.add_argument("-t", "--tableheaders", 
            default=False,
            help= \
               "-t True specifies table includes a header row.")
        args = parser.parse_args()
        print('Delimiter = %s'%(args.delimiter))
        return args

    def appMain(self):
        args = self.getArgs()
        if (args.inputfile):
            from pywikitable import pywikitable
            app = WikiTable()
            app.appMain(args.inputfile, args.outputfile, 
                              args.delimiter, args.tableheaders)
        else:
            from gui import wikiWin
            app=wikiWin(RUN=True)
"""
Main program - run stand-alone if not included as part of a larger application
"""
if __name__ == '__main__':
   app = theApp()
